"""Phase 2 controlled scenarios, preserved VERBATIM from the original notebook.

``PHASE2_SAMPLES`` is copied cell-for-cell from
``ProvenanceLens_Phase2 (1).ipynb`` (cell 5).

``PHASE2_EXPECTED`` was generated by EXECUTING THE ORIGINAL NOTEBOOK CODE and
capturing its full result dicts — it is ground truth for the prototype's
behavior, not an assertion written to fit a refactor.
"""

PHASE2_SAMPLES = [
    {
        "model_id": "demo/missing-lineage-model",
        "metadata": {"base_model": None, "base_model_relation": None},
        "config": {"_name_or_path": "meta-llama/Llama-3.2-1B"},
        "readme": "This model was fine-tuned from meta-llama/Llama-3.2-1B for instruction following.",
        "tool_errors": [],
    },
    {
        "model_id": "demo/conflicting-lineage-model",
        "metadata": {"base_model": "mistralai/Mistral-7B-v0.1", "base_model_relation": "fine-tune"},
        "config": {"_name_or_path": "meta-llama/Llama-3.2-1B"},
        "readme": "This model was fine-tuned from meta-llama/Llama-3.2-1B.",
        "tool_errors": [],
    },
    {
        "model_id": "demo/correct-lineage-model",
        "metadata": {"base_model": "meta-llama/Llama-3.2-1B", "base_model_relation": "fine-tune"},
        "config": {"_name_or_path": "meta-llama/Llama-3.2-1B"},
        "readme": "This model was fine-tuned from meta-llama/Llama-3.2-1B.",
        "tool_errors": [],
    },
    {
        "model_id": "demo/ambiguous-lineage-model",
        "metadata": {"base_model": None, "base_model_relation": None},
        "config": {"_name_or_path": "Qwen/Qwen2.5-1.5B"},
        "readme": "This model was fine-tuned from meta-llama/Llama-3.2-1B.",
        "tool_errors": [],
    },
    {
        "model_id": "demo/tool-failure-model",
        "metadata": {"base_model": None, "base_model_relation": None},
        "config": {},
        "readme": "",
        "tool_errors": ["README retrieval timed out", "config.json unavailable"],
    },
]

PHASE2_EXPECTED = [
    {
        "model_id": "demo/missing-lineage-model",
        "action": "ADD",
        "proposed_parent": "meta-llama/Llama-3.2-1B",
        "relationship": "fine-tune",
        "confidence": 0.9,
        "supporting_evidence": [
            "config.json: meta-llama/Llama-3.2-1B (fine-tune)",
            "README: meta-llama/Llama-3.2-1B (fine-tune)",
        ],
        "conflicting_evidence": [],
        "rationale": "The strongest parent is independently supported by configuration and documentation.",
    },
    {
        "model_id": "demo/conflicting-lineage-model",
        "action": "REPLACE",
        "proposed_parent": "meta-llama/Llama-3.2-1B",
        "relationship": "fine-tune",
        "confidence": 0.9,
        "supporting_evidence": [
            "config.json: meta-llama/Llama-3.2-1B (fine-tune)",
            "README: meta-llama/Llama-3.2-1B (fine-tune)",
        ],
        "conflicting_evidence": ["declared metadata: mistralai/Mistral-7B-v0.1"],
        "rationale": "The strongest parent is independently supported by configuration and documentation.",
    },
    {
        "model_id": "demo/correct-lineage-model",
        "action": "KEEP",
        "proposed_parent": "meta-llama/Llama-3.2-1B",
        "relationship": "fine-tune",
        "confidence": 0.9,
        "supporting_evidence": [
            "config.json: meta-llama/Llama-3.2-1B (fine-tune)",
            "README: meta-llama/Llama-3.2-1B (fine-tune)",
        ],
        "conflicting_evidence": [],
        "rationale": "The strongest parent is independently supported by configuration and documentation.",
    },
    {
        "model_id": "demo/ambiguous-lineage-model",
        "action": "ABSTAIN",
        "proposed_parent": None,
        "relationship": None,
        "confidence": 0.45,
        "supporting_evidence": ["config.json: Qwen/Qwen2.5-1.5B (fine-tune)"],
        "conflicting_evidence": ["README: meta-llama/Llama-3.2-1B"],
        "rationale": "The evidence is conflicting or does not meet the minimum support threshold.",
    },
    {
        "model_id": "demo/tool-failure-model",
        "action": "ABSTAIN",
        "proposed_parent": None,
        "relationship": None,
        "confidence": 0.1,
        "supporting_evidence": [],
        "conflicting_evidence": ["README retrieval timed out", "config.json unavailable"],
        "rationale": "Evidence is unavailable or insufficient for a safe repair.",
    },
]

# Expected decision per scenario, as approved for Phase B regression.
PHASE2_EXPECTED_ACTIONS = ["ADD", "REPLACE", "KEEP", "ABSTAIN", "ABSTAIN"]
